### ISSUE TITLE
encryption not supported

### ISSUE THREAD

**Issue by ghost** [TwrpBuilder/android_device_ZTE_jasmine#1]
I see that it is not yet compatible with encryption

**Comment by ghost** [comment]
Twrp for jasmine is dead

**Comment by androidlover5842** [comment]
is there any issue in new version ?

**Comment by ghost** [comment]
> is there any issue in new version ?

one only in one version in all the version, I know that the encryption does not work, but when I delete the encryption and install the new rom I do not boot and to boot I have to use this file to patch boot no-verity-opt-encrypt -6.0.zip and every new ROM I have to do

apparently the ROM of my developed only supports twrp encryption. the developed is tdm in xda

**Comment by ghost** [comment]
it is better to erase the repo of my device, Because there is someone who has a problem with this TWRP and the developer updated it

**Comment by yshalsager** [comment]
the solution is super easy, once you install twrp, format data for once time and use magisk to patch boot after flashing the rom.

**Comment by ghost** [comment]
> the solution is super easy, once you install twrp, format data for once time and use magisk to patch boot after flashing the rom.

bro, I do not use magisk.
know better to close this issue or delete the repo of jasmine because there is already a lot of user that bricked to this device for not knowing this

**Comment by ghost** [comment]
> the solution is super easy, once you install twrp, format data for once time and use magisk to patch boot after flashing the rom.

Because there is someone who has a problem with this TWRP and the developer updated it

**Comment by yshalsager** [comment]
Check this if you don't want magisk 
https://forum.xda-developers.com/android/software/universal-dm-verity-forceencrypt-t3817389
@junior012

**Comment by ghost** [comment]
I already know that

**Comment by surendrajat** [comment]
Good then..

**Comment by ghost** [comment]
great😒
